matrix:
  include:
    - stage: front
      language: node_js
      node_js: 11
      before_install: cd client
      install: npm install
      script: 
        - npm run tslint
        - npm run build
    - stage: back
      language: rust
      script:
        - cargo test --all
        - cargo build --all
cache:
  - cargo
  - npm
