language: rust
rust:
    - stable
cache: cargo
script:
    - cd client && npm install && npm run build && cd ..
    - cd mobile && npm install && npm run build && cd ..
    - cargo build --all
    - cargo test --all
