version: '3'
services:
    mindstream_postgres:
        image: postgres:10.0-alpine
        environment:
            POSTGRES_PASSWORD: mindstream
            POSTGRES_USER: mindstream
            POSTGRES_DB: mindstream
        ports:
            - 5432:5432
        volumes:
            - .docker-data/postgresql:/var/lib/postgresql/data

    mindstream_adminer:
        image: adminer
        ports:
            - 5555:8080
        depends_on:
            - mindstream_postgres

