version: '2'
services:
    postgres:
        image: postgres:10.0-alpine
        environment:
            POSTGRES_PASSWORD: mindstream
            POSTGRES_USER: mindstream
            POSTGRES_DB: mindstream
        ports:
            - 5432:5432
        volumes:
            - .docker-data/postgresql:/var/lib/postgresql/data

    adminer:
        image: adminer
        ports:
            - 5555:8080
        depends_on:
            - postgres

    zookeeper:
        image: wurstmeister/zookeeper:latest
        ports:
            - "2181:2181"
    kafka:
        image: wurstmeister/kafka:latest
        ports:
            - "9092:9092"
        environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_HOST_NAME: localhost
            KAFKA_CREATE_TOPICS: "topic1:1:1"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
