# Check https://circleci.com/docs/2.0
version: 2
jobs:
  build-front:
    docker:
      - image: circleci/node:12.0.0
    working_directory: ~/repo/client
    steps:
      - checkout:
          path: ~/repo

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm i

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run tslint
      - run: npm run build

      - persist_to_workspace:
          root: ~/repo
          paths: static

  build-mobile:
    docker:
      - image: circleci/node:12.0.0
    working_directory: ~/repo/mobile
    steps:
      - checkout:
          path: ~/repo

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm i

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run tslint
      - run: npm run tsc

  build-api:
    docker:
      - image: circleci/rust:1.34.1-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      
      - run: rustup component add clippy
      - run: cargo clippy -- -D warnings
      - run: cargo test
      - run: cargo build --release

      - save_cache:
          paths:
            - ~/.cargo
            - /usr/local/cargo/registry
            - target
          key: v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}

      - persist_to_workspace:
          root: ~/repo
          paths: target/release/mindstream

  deploy-docker:
    docker:
      - image: circleci/node:12.0.0
    working_directory: ~/repo
    steps:
      - checkout

      - attach_workspace:
          at: ~/repo

      - setup_remote_docker

      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Docker build
          command: |
            mkdir build
            cp -r static build/static && cp target/release/mindstream build/mindstream && cp Dockerfile build/Dockerfile
            cd build
            docker build -f Dockerfile -t wadjetz/mindstream .

      - run: docker push wadjetz/mindstream

  deploy-docker-branch:
    docker:
      - image: circleci/node:12.0.0
    working_directory: ~/repo
    steps:
      - checkout

      - attach_workspace:
          at: ~/repo

      - setup_remote_docker

      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Docker build
          command: |
            mkdir build
            cp -r static build/static && cp target/release/mindstream build/mindstream && cp Dockerfile build/Dockerfile
            cd build
            docker build -f Dockerfile -t wadjetz/mindstream:$CIRCLE_BRANCH .

      - run: docker push wadjetz/mindstream:$CIRCLE_BRANCH

workflows:
  version: 2
  mindstream:
    jobs:
      - build-front
      - build-api
      - build-mobile
      - deploy-docker:
          requires:
            - build-front
            - build-api
            - build-mobile
          filters:
            branches:
              only: master
      - deploy-docker-branch:
          requires:
            - build-front
            - build-api
            - build-mobile
